# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(default='perro', max_length=10),
            preserve_default=False,
        ),
    ]
